sudo: required
dist: trusty
language: node_js
node_js:
  - "6"
before_script:
  - psql -c 'create database database_test;' -U postgres
  - npm i -g sequelize-cli
  - sequelize db:migrate --env=test
  - sequelize db:seed --env=test
script:
- npm test
after_script:
  - npm run coveralls
services:
  - postgresql