sudo: required
dist: trusty
language: node_js
node_js:
  - "6"
script:
- npm test
after_script:
  - npm run coveralls
before_script:
  - psql -c 'create database database_test;' -U postgres
services:
  - postgresql